version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "127.0.0.1:8010:8010"     # ← bind host localhost:8010 → container:8010
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - S3_BUCKET=my-bucket
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
    depends_on:
      - redis
      - worker

  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - S3_BUCKET=my-bucket
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"