version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "[%(asctime)s] %(levelname)-8s %(name)s: %(message)s"

handlers:
  uvicorn_file:
    class: logging.handlers.RotatingFileHandler
    filename: /var/log/myapp/uvicorn.log
    maxBytes: 10485760   # 10 MB
    backupCount: 5
    formatter: standard

  celery_file:
    class: logging.handlers.RotatingFileHandler
    filename: /var/log/myapp/celery.log
    maxBytes: 10485760
    backupCount: 5
    formatter: standard

loggers:
  uvicorn:
    handlers: [uvicorn_file]
    level: INFO
    propagate: no

  uvicorn.error:
    handlers: [uvicorn_file]
    level: INFO
    propagate: no

  uvicorn.access:
    handlers: [uvicorn_file]
    level: INFO
    propagate: no

  celery:
    handlers: [celery_file]
    level: INFO
    propagate: no

root:
  level: INFO
  handlers: []